title: A Mathematical Blog
author: Hari Seldon
email: aiv4eizooca8ojareigh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal effort to keep learning math after my Ph.D.
  I am currently working in the industry, and want to keep learning
  at my own pace aspects of Mathematical Physics and Machine learning.

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
highlighter: pygments
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
